language: python
services:
- postgresql
python:
- '3.5'
addons:
  postgresql: "9.4"
install:
- pip install -r requirements.txt
- pip install -r requirements_test.txt
- cp devcentry/local_settings_travis.py devcentry/local_settings.py
before_script:
  - psql -c "CREATE ROLE devcentry LOGIN PASSWORD 'devcentry' NOSUPERUSER INHERIT CREATEDB NOCREATEROLE NOREPLICATION;" -U postgres
  - psql -c "CREATE DATABASE test_devcentry WITH OWNER = devcentry ENCODING = 'UTF8' CONNECTION LIMIT = -1;" -U postgres
script:
  - pep8 .
  - python manage.py test --noinput